
export const GET_PRODUCTS_LOADING="GET_PRODUCTS_LOADING";
export const GET_PRODUCTS_SUCCESS="GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAILD="GET_PRODUCTS_FAILD";


export const GET_CART_SUCCESS="GET_CART_SUCCESS";
export const GET_CART_FAILD="GET_CART_FAILD";
